service: aws-nodejs # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

functions:
  get:
    handler: lambdas/get.get
    events:
      -  http:
          path: get
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  post:
    handler: lambdas/post.post
    events:
      - http:
          path: post
          method: post
    request:
        passThrough: WHEN_NO_TEMPLATES
        template:
          application/x-www-form-urlencoded: '{ "body" : "$input.body" }'

  update:
    handler: lambdas/update.update
    events:
      - http:
          path: update
          method: update

  delete:
    handler: lambdas/delete.delete
    events:
      - http:
          path: delete
          method: delete
